name: fresh_admin_dashboard
description: Minimal Flutter Web Admin Dashboard skeleton (Login + Dashboard + Sidebar + Reports + Settings)
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
